version: '3.8'

# Development Environment for Ubuntu VM
# Uses bind mounts for live code editing with hot reload

services:
  # MariaDB Cache Database
  mariadb:
    image: docker.io/library/mariadb:10.11
    container_name: genealogy-mariadb-dev
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-genealogy_cache}
      MARIADB_USER: ${MARIADB_USER:-genealogy}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/migrations/003_fact_based_schema.sql:/docker-entrypoint-initdb.d/02-facts.sql:ro
      - ./database/migrations/004_resolution_workflow.sql:/docker-entrypoint-initdb.d/03-resolution.sql:ro
    networks:
      - genealogy-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "127.0.0.1:3306:3306"  # Only expose to localhost

  # Backend API Server (Development Mode)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: genealogy-backend-dev
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      # External Gramps Web Configuration
      GRAMPS_WEB_URL: ${GRAMPS_WEB_URL}
      GRAMPS_USERNAME: ${GRAMPS_USERNAME}
      GRAMPS_PASSWORD: ${GRAMPS_PASSWORD}
      
      # MariaDB Configuration
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: ${MARIADB_USER:-genealogy}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-genealogy_cache}
      
      # Application Configuration
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      ENVIRONMENT: development
      
      # Development Features
      RELOAD: "true"  # Enable uvicorn auto-reload
    volumes:
      # Bind mount source code for live editing
      - ./backend:/app:rw
      # Separate volume for logs (writable)
      - backend_logs:/app/logs
    networks:
      - genealogy-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8000:8000"
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --log-level debug

  # Frontend Web Application (Development Mode)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: genealogy-frontend-dev
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
      NODE_ENV: development
    volumes:
      # Bind mount source code for live editing
      - ./frontend:/app:rw
      # Exclude node_modules from bind mount (performance)
      - /app/node_modules
    networks:
      - genealogy-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "5173:5173"  # Vite dev server port
    command: npm run dev -- --host 0.0.0.0

networks:
  genealogy-net:
    driver: bridge
    name: genealogy-net-dev

volumes:
  mariadb_data:
    name: genealogy-mariadb-data-dev
  backend_logs:
    name: genealogy-backend-logs-dev
