version: '3.8'

services:
  mariadb:
    image: docker.io/library/mariadb:10.11
    container_name: genealogy-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-genealogy_cache}
      MARIADB_USER: ${MARIADB_USER:-genealogy}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - genealogy-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: genealogy-backend
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: ${MARIADB_USER:-genealogy}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-genealogy_cache}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      GRAMPS_WEB_URL: ${GRAMPS_WEB_URL}
      GRAMPS_USERNAME: ${GRAMPS_USERNAME}
      GRAMPS_PASSWORD: ${GRAMPS_PASSWORD}
      GRAMPS_API_TOKEN: ${GRAMPS_API_TOKEN:-}
    volumes:
      - ./backend:/app:rw
    networks:
      - genealogy-net
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

networks:
  genealogy-net:
    driver: bridge

volumes:
  mariadb_data:
